# 设置端口
server:
  port: 8080

# 设置数据源
# mysql时区临时处理: serverTimezone=GMT%2B8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/information_schema?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池配置
    druid:
      # 最小数
      min-idle: 5
      # 最大数
      max-active: 20
      # 初始大小
      initial-size: 5
      # 配置获取连接等待超时时间
      max-wait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间  单位为毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filters: stat,wall

# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 全局的映射，不用在xml文件写实体类的全路径
  type-aliases-package: com.wxw.domain
  configuration:
    # 开启MyBatis的二级缓存
    cache-enabled: true
    # 控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰映射
    map-underscore-to-camel-case: true

